[package]
name = "rust-axum-api"
version = "1.0.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing-subscriber = "0.3.20"